export default {
  appTitle: 'Untitled Karaoke App',
  cancel: 'Cancel',
  next: 'Next',
  songsEmptySet: 'Your playlist is empty.',
  roomAddSong: 'Add Song',
  roomAddFavorite: 'Add favorite',
  roomTvView: 'TV mode',
  songSearch: 'Search Videos',
  createRoomTitle: 'Create Room',
  addSongTitle: 'Add Song to Queue',
  searchLabel: 'Search YouTube videos',
  searchButton: 'Search',
  joinRoomTitle: roomName => `Join ${roomName}`,
  joinRoomName: 'Name',
  joinRoomPassword: 'Password',
  joinRoomButton: 'Join',
  animalName: animal => `Anonymous ${animal}`,
  favoritesTitle: 'Favorites',
  favoritesEmpty: "You don't have any favorite videos.",
  addRoomLink: 'Create Room',
  editRoomLink: 'Edit Room',
  favoritesLink: 'Favorites',
  historyTitle: 'History',
  historyEmpty: 'You have not sung any songs yet in this room',
  historyLink: 'History',
  searchLink: 'Search',
  play: 'Play Song',
  pause: 'Pause Song',
  nextSong: 'Next Song',
  exitRoom: 'Exit Room',
};
