export default {
  cancel: 'Cancel',
  songsEmptySet: 'Your playlist is empty.',
  roomAddSong: 'Add song',
  roomAddFavorite: 'Add favorite',
  songSearch: 'Search Videos',
  searchTitle: roomName => `Add song to ${roomName}`,
  searchLabel: 'Search YouTube videos',
  searchButton: 'Search',
  joinRoomTitle: roomName => `Join ${roomName}`,
  joinRoomName: 'Name',
  joinRoomPassword: 'Password',
  joinRoomButton: 'Join',
  favoritesTitle: 'Favorites',
  favoritesEmpty: "You don't have any favorite videos.",
};
