export default {
  cancel: 'Cancel',
  songsEmptySet: 'Your playlist is empty.',
  roomAddSong: 'Add song',
  roomAddFavorite: 'Add favorite',
  roomTvView: 'TV mode',
  songSearch: 'Search Videos',
  searchTitle: roomName => `Add song to ${roomName}`,
  searchLabel: 'Search YouTube videos',
  searchButton: 'Search',
  joinRoomTitle: roomName => `Join ${roomName}`,
  joinRoomName: 'Name',
  joinRoomPassword: 'Password',
  joinRoomButton: 'Join',
  animalName: animal => `Anonymous ${animal}`,
  favoritesTitle: 'Favorites',
  favoritesEmpty: "You don't have any favorite videos.",
  addRoomLink: 'Add Room',
  play: 'Play Song',
  pause: 'Pause Song',
  nextSong: 'Next Song',
  exitRoom: 'Exit Room',
};
